version: '3.8'

services:
  db:
    image: postgres:17-alpine
    container_name: despachos_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_DB: despachos_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  db_flota:
    image: postgres:17-alpine
    container_name: flota_postgres
    restart: always
    environment:
      POSTGRES_USER: flota_user
      POSTGRES_PASSWORD: flotapassword
      POSTGRES_DB: flota_db
    ports:
      - "5433:5432"
    volumes:
      - flota_postgres_data:/var/lib/postgresql/data

  api_despachos:
    build:
      context: ./API_Despachos
      dockerfile: Dockerfile
    container_name: despachos_api
    restart: always
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgrespassword@db:5432/despachos_db
      - PORT=8000
    depends_on:
      - db
  
  grpc_flota:
    build:
      context: ./gRPC_Flota
      dockerfile: Dockerfile
    container_name: flota_grpc
    restart: always
    ports:
      - "50051:50051"
    environment:
      - DATABASE_URL="postgresql+psycopg2://flota_user:flotapassword@localhost:5432/flota_db"
    depends_on:
      - db_flota

volumes:
  despachos_postgres_data:
  flota_postgres_data: