# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import flota_pb2 as flota__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in flota_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ServicioFlotaStub:
    """Definición del Servicio (Las "funciones" que Despachos podrá llamar)
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ConsultarCamion = channel.unary_unary(
                '/flota.v1.ServicioFlota/ConsultarCamion',
                request_serializer=flota__pb2.ConsultarCamionRequest.SerializeToString,
                response_deserializer=flota__pb2.ConsultarCamionResponse.FromString,
                _registered_method=True)
        self.ListarFlota = channel.unary_unary(
                '/flota.v1.ServicioFlota/ListarFlota',
                request_serializer=flota__pb2.ListarFlotaRequest.SerializeToString,
                response_deserializer=flota__pb2.ListarFlotaResponse.FromString,
                _registered_method=True)
        self.ActualizarCapacidad = channel.unary_unary(
                '/flota.v1.ServicioFlota/ActualizarCapacidad',
                request_serializer=flota__pb2.ActualizarCapacidadRequest.SerializeToString,
                response_deserializer=flota__pb2.ActualizarCapacidadResponse.FromString,
                _registered_method=True)


class ServicioFlotaServicer:
    """Definición del Servicio (Las "funciones" que Despachos podrá llamar)
    """

    def ConsultarCamion(self, request, context):
        """Consultar un camión y su capacidad de carga disponible
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListarFlota(self, request, context):
        """Listar la flota y sus rutas
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ActualizarCapacidad(self, request, context):
        """Ocupar o liberar capacidad (para reflejar el despacho o su cancelación)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ServicioFlotaServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ConsultarCamion': grpc.unary_unary_rpc_method_handler(
                    servicer.ConsultarCamion,
                    request_deserializer=flota__pb2.ConsultarCamionRequest.FromString,
                    response_serializer=flota__pb2.ConsultarCamionResponse.SerializeToString,
            ),
            'ListarFlota': grpc.unary_unary_rpc_method_handler(
                    servicer.ListarFlota,
                    request_deserializer=flota__pb2.ListarFlotaRequest.FromString,
                    response_serializer=flota__pb2.ListarFlotaResponse.SerializeToString,
            ),
            'ActualizarCapacidad': grpc.unary_unary_rpc_method_handler(
                    servicer.ActualizarCapacidad,
                    request_deserializer=flota__pb2.ActualizarCapacidadRequest.FromString,
                    response_serializer=flota__pb2.ActualizarCapacidadResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'flota.v1.ServicioFlota', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('flota.v1.ServicioFlota', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ServicioFlota:
    """Definición del Servicio (Las "funciones" que Despachos podrá llamar)
    """

    @staticmethod
    def ConsultarCamion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/flota.v1.ServicioFlota/ConsultarCamion',
            flota__pb2.ConsultarCamionRequest.SerializeToString,
            flota__pb2.ConsultarCamionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListarFlota(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/flota.v1.ServicioFlota/ListarFlota',
            flota__pb2.ListarFlotaRequest.SerializeToString,
            flota__pb2.ListarFlotaResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ActualizarCapacidad(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/flota.v1.ServicioFlota/ActualizarCapacidad',
            flota__pb2.ActualizarCapacidadRequest.SerializeToString,
            flota__pb2.ActualizarCapacidadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
