# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: flota.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'flota.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x66lota.proto\x12\x08\x66lota.v1\"+\n\x16\x43onsultarCamionRequest\x12\x11\n\tcamion_id\x18\x01 \x01(\t\"\\\n\x17\x43onsultarCamionResponse\x12\x11\n\tcamion_id\x18\x01 \x01(\t\x12\x1f\n\x17\x63\x61pacidad_disponible_kg\x18\x02 \x01(\x01\x12\r\n\x05rutas\x18\x03 \x03(\t\"\x14\n\x12ListarFlotaRequest\"J\n\x13ListarFlotaResponse\x12\x33\n\x08\x63\x61miones\x18\x01 \x03(\x0b\x32!.flota.v1.ConsultarCamionResponse\"E\n\x1a\x41\x63tualizarCapacidadRequest\x12\x11\n\tcamion_id\x18\x01 \x01(\t\x12\x14\n\x0cvariacion_kg\x18\x02 \x01(\x01\"_\n\x1b\x41\x63tualizarCapacidadResponse\x12\r\n\x05\x65xito\x18\x01 \x01(\x08\x12\x1a\n\x12nueva_capacidad_kg\x18\x02 \x01(\x01\x12\x15\n\rmensaje_error\x18\x03 \x01(\t2\x97\x02\n\rServicioFlota\x12V\n\x0f\x43onsultarCamion\x12 .flota.v1.ConsultarCamionRequest\x1a!.flota.v1.ConsultarCamionResponse\x12J\n\x0bListarFlota\x12\x1c.flota.v1.ListarFlotaRequest\x1a\x1d.flota.v1.ListarFlotaResponse\x12\x62\n\x13\x41\x63tualizarCapacidad\x12$.flota.v1.ActualizarCapacidadRequest\x1a%.flota.v1.ActualizarCapacidadResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'flota_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CONSULTARCAMIONREQUEST']._serialized_start=25
  _globals['_CONSULTARCAMIONREQUEST']._serialized_end=68
  _globals['_CONSULTARCAMIONRESPONSE']._serialized_start=70
  _globals['_CONSULTARCAMIONRESPONSE']._serialized_end=162
  _globals['_LISTARFLOTAREQUEST']._serialized_start=164
  _globals['_LISTARFLOTAREQUEST']._serialized_end=184
  _globals['_LISTARFLOTARESPONSE']._serialized_start=186
  _globals['_LISTARFLOTARESPONSE']._serialized_end=260
  _globals['_ACTUALIZARCAPACIDADREQUEST']._serialized_start=262
  _globals['_ACTUALIZARCAPACIDADREQUEST']._serialized_end=331
  _globals['_ACTUALIZARCAPACIDADRESPONSE']._serialized_start=333
  _globals['_ACTUALIZARCAPACIDADRESPONSE']._serialized_end=428
  _globals['_SERVICIOFLOTA']._serialized_start=431
  _globals['_SERVICIOFLOTA']._serialized_end=710
# @@protoc_insertion_point(module_scope)
